### ISSUE TITLE
No alive nodes found in your cluster

### ISSUE THREAD

**Issue by tripleten** [elastic/elasticsearch-php#1094]
I am using Laravel 8 and Elasticsearch version 7.10.0, my environment details are below:

"php": "^7.3|^8.0",
"cviebrock/laravel-elasticsearch": "^8.0",
"elasticsearch/elasticsearch": "^7.10",
"fideloper/proxy": "^4.4",
"fruitcake/laravel-cors": "^2.0",
"guzzlehttp/guzzle": "^7.0.1",
"laravel/framework": "^8.12",
"laravel/tinker": "^2.5",
"laravel/ui": "^3.1",
"league/csv": "^9.6",
"spatie/laravel-permission": "^3.17",
"yajra/laravel-datatables-oracle": "^9.14"

Also, the elasticsearch host and other details as in the .env file are below:

ELASTICSEARCH_HOST="https://7e93d3d57e624dfeb051a57cb113171c.ap-south-1.aws.elastic-cloud.com"
ELASTICSEARCH_PORT=9243
ELASTICSEARCH_SCHEME=https
ELASTICSEARCH_USER=******
ELASTICSEARCH_PASS=**********

Could you please suggest what could be the possible reason for this not working from my localhost ( XAMPP running on Windows 10 )?

**Note**: I used the same code to run on the CentOS but got the same error.

**Comment by ezimuel** [comment]
@tripleten I'm not familiar with the `Elasticsearch` integration in `Laravel`, that said according to your configuration (.env) the `Elasticsearch\Client` needs the following parameter:
```php
use Elasticsearch\ClientBuilder;

$client = ClientBuilder::create()
    ->setHosts(['https://7e93d3d57e624dfeb051a57cb113171c.ap-south-1.aws.elastic-cloud.com:9243'])
    ->setBasicAuthentication('***','***')
    ->build();
```
Are you sure the port is `9243`? Usually for AWS is the standard `443` (https).
Please give a try and let me know, thanks!

**Comment by Smokietr** [comment]
Unfortunately I have the same problem and what I did did not work. I tried it separately on Amazon and Azure. I have used Elasticsearch before and it has huge problems with stability. Please pay more attention to this issue. As for my problem, I tried it as the URL.

Ex: https: // elastic: password @ host: port

I tried ports 443, 80, 9243 all. By the way, it works on localhost without any problem.

It is also not being debugged properly !!! It is very inadequate.

Yes, if we come to the codes I have tried:

```PHP
\Elasticsearch\ClientBuilder::create()->setHosts([
            [
                'host' => '***ee421c2934.westeurope.azure.elastic-cloud.com',
                'scheme' => 'https',
                'port' => 443
            ]
])->setBasicAuthentication('***', '***')->build();

```

```PHP
\Elasticsearch\ClientBuilder::fromConfig(['hosts' => ['https://user:pass@***ee421c2934.westeurope.azure.elastic-cloud.com:443']])
```
I have tried different versions of Elasticsearch. Last try.

```JSON
{
    "name": "instance-0000000000",
    "cluster_name": "***ee421c2934",
    "cluster_uuid": "_iHIgEPbSHS732lMJp9bQQ",
    "version": {
        "number": "6.8.13",
        "build_flavor": "default",
        "build_type": "tar",
        "build_hash": "be13c69",
        "build_date": "2020-10-16T09:09:46.555371Z",
        "build_snapshot": false,
        "lucene_version": "7.7.3",
        "minimum_wire_compatibility_version": "5.6.0",
        "minimum_index_compatibility_version": "5.0.0"
    },
    "tagline": "You Know, for Search"
}
```

I have also tried PHP 8, 7.3.5, 7.2.18 and Elasticsearh Libraries 6.1, 7.x, 7.9.1.

**Comment by ezimuel** [comment]
@Smokietr I didn't undertstand if you are trying to connect to Elasticsearch using Amazon Elasticsearch Service or Elastic Cloud or if you have your custom Elasticsearch server running on Azure or AWS cloud. Regarding the debug issue, did you try to enable a logger to check for HTTP request and response? You can have a look [here](https://github.com/elastic/elasticsearch-php/blob/master/docs/configuration.asciidoc#enabling-the-logger) for enable logging.
I'm sorry for this issue, I'm here to help.

**Comment by valehasadli** [comment]
Is anyone found a solution?

**Comment by damianoi** [comment]
@valehasadli @ezimuel 
I'm experienced the same issue using `cviebrock/laravel-elasticsearch` and then I switched to "pure" `elasticsearch/elasticsearch` (7.14), but the issue is still there.

You can find my comment about this here:
[https://github.com/elastic/elasticsearch-php/issues/1146#issuecomment-902030924](url)

**Comment by valehasadli** [comment]
> I am using Laravel 8 and Elasticsearch version 7.10.0, my environment details are below:
> 
> "php": "^7.3|^8.0",
> "cviebrock/laravel-elasticsearch": "^8.0",
> "elasticsearch/elasticsearch": "^7.10",
> "fideloper/proxy": "^4.4",
> "fruitcake/laravel-cors": "^2.0",
> "guzzlehttp/guzzle": "^7.0.1",
> "laravel/framework": "^8.12",
> "laravel/tinker": "^2.5",
> "laravel/ui": "^3.1",
> "league/csv": "^9.6",
> "spatie/laravel-permission": "^3.17",
> "yajra/laravel-datatables-oracle": "^9.14"
> 
> Also, the elasticsearch host and other details as in the .env file are below:
> 
> ELASTICSEARCH_HOST="https://7e93d3d57e624dfeb051a57cb113171c.ap-south-1.aws.elastic-cloud.com"
> ELASTICSEARCH_PORT=9243
> ELASTICSEARCH_SCHEME=https
> ELASTICSEARCH_USER=******
> ELASTICSEARCH_PASS=**********
> 
> Could you please suggest what could be the possible reason for this not working from my localhost ( XAMPP running on Windows 10 )?
> 
> **Note**: I used the same code to run on the CentOS but got the same error.

`setHosts` method should use with this array 

```
'hosts' => [
       [
           'host' => env('ELASTIC_HOST', 'url_custom'),
           'scheme' => 'https',
           'port' => 443,
       ]
    ]
```

**Comment by valehasadli** [comment]
> @valehasadli @ezimuel
> I'm experienced the same issue using `cviebrock/laravel-elasticsearch` and then I switched to "pure" `elasticsearch/elasticsearch` (7.14), but the issue is still there.
> 
> You can find my comment about this here:
> [https://github.com/elastic/elasticsearch-php/issues/1146](url)

The low-level client has the same problem, the code I mentioned above fixed my problem.

**Comment by damianoi** [comment]
> `setHosts` method should use with this array
> 
> ```
> 'hosts' => [
>        [
>            'host' => env('ELASTIC_HOST', 'url_custom'),
>            'scheme' => 'https',
>            'port' => 443,
>        ]
>     ]
> ```

Hi @valehasadli thank you for your help. Btw  I tried the way you shown me, unfortunately without any success.

This is the way I modified the code after your comment:
```
$clientBuilder->setHosts([
            'hosts' => [
                [
                    'host' => 'localhost',
                    'scheme' => 'http',
                    'port' => 9200,
                ]
            ]
        ]);
```
But what I obtained was a 500 error:
```
Required 'host' was not defined in extended format: Array
(
[0] => Array
(
[host] => localhost
[scheme] => http
[port] => 9200
)

)
```

And the log file reports:
```
[2021-08-20T09:37:01.556068+00:00] name.WARNING: Curl exception encountered. [] []
[2021-08-20T09:37:01.560896+00:00] name.DEBUG: Request Body [null] []
[2021-08-20T09:37:01.561542+00:00] name.WARNING: Request Failure: {"method":"GET","uri":"http://localhost/test-index/_stats","headers":{"Host":["localhost"],"Content-Type":["application/json"],"Accept":["application/json"],"User-Agent":["elasticsearch-php/7.0.0 (Linux 5.10.25-linuxkit; PHP 7.4.20)"]},"HTTP code":null,"duration":0.001508,"error":"cURL error 7: Failed to connect to localhost port 9200: Connection refused"} []
[2021-08-20T09:37:01.562262+00:00] name.WARNING: Response [null] []
[2021-08-20T09:37:01.562759+00:00] name.WARNING: Marking node localhost dead. [] []
[2021-08-20T09:37:01.563430+00:00] name.WARNING: Retries left? true [] []
[2021-08-20T09:37:01.565845+00:00] name.CRITICAL: No alive nodes found in cluster [] []
[2021-08-20T09:37:10.363370+00:00] name.ERROR: Required 'host' was not defined in extended format: Array (     [0] => Array         (             [host] => localhost             [scheme] => http             [port] => 9200         )  )  [] []
```

Maybe I'm doing something wrong?

**Comment by valehasadli** [comment]
> > `setHosts` method should use with this array
> > ```
> > 'hosts' => [
> >        [
> >            'host' => env('ELASTIC_HOST', 'url_custom'),
> >            'scheme' => 'https',
> >            'port' => 443,
> >        ]
> >     ]
> > ```
> 
> Hi @valehasadli thank you for your help. Btw I tried the way you shown me, unfortunately without any success.
> 
> This is the way I modified the code after your comment:
> 
> ```
> $clientBuilder->setHosts([
>             'hosts' => [
>                 [
>                     'host' => 'localhost',
>                     'scheme' => 'http',
>                     'port' => 9200,
>                 ]
>             ]
>         ]);
> ```
> 
> But what I obtained was a 500 error:
> 
> ```
> Required 'host' was not defined in extended format: Array
> (
> [0] => Array
> (
> [host] => localhost
> [scheme] => http
> [port] => 9200
> )
> 
> )
> ```
> 
> And the log file reports:
> 
> ```
> [2021-08-20T09:37:01.556068+00:00] name.WARNING: Curl exception encountered. [] []
> [2021-08-20T09:37:01.560896+00:00] name.DEBUG: Request Body [null] []
> [2021-08-20T09:37:01.561542+00:00] name.WARNING: Request Failure: {"method":"GET","uri":"http://localhost/test-index/_stats","headers":{"Host":["localhost"],"Content-Type":["application/json"],"Accept":["application/json"],"User-Agent":["elasticsearch-php/7.0.0 (Linux 5.10.25-linuxkit; PHP 7.4.20)"]},"HTTP code":null,"duration":0.001508,"error":"cURL error 7: Failed to connect to localhost port 9200: Connection refused"} []
> [2021-08-20T09:37:01.562262+00:00] name.WARNING: Response [null] []
> [2021-08-20T09:37:01.562759+00:00] name.WARNING: Marking node localhost dead. [] []
> [2021-08-20T09:37:01.563430+00:00] name.WARNING: Retries left? true [] []
> [2021-08-20T09:37:01.565845+00:00] name.CRITICAL: No alive nodes found in cluster [] []
> [2021-08-20T09:37:10.363370+00:00] name.ERROR: Required 'host' was not defined in extended format: Array (     [0] => Array         (             [host] => localhost             [scheme] => http             [port] => 9200         )  )  [] []
> ```
> 
> Maybe I'm doing something wrong?

client by default use `9200` port. Are you make sure that your elastic client is up? Have you ever test with cURl requests?

**Comment by damianoi** [comment]
@valehasadli I really appreciate your help and finally I solved! You can find details below. :)


**Update:**
I'm having two different docker containers: one for elasticsearch instance and the other for laravel instance.
Obviously the two containers were not "talking" each other.
I solved creating a network between these different container and using the local IP (172. ...) assigned to the elasticsearch one into the laravel instance.
Now it works perfectly.

**Comment by valehasadli** [comment]
> @valehasadli I really appreciate your help and finally I solved! You can find details below. :)
> 
> **Update:**
> I'm having two different docker containers: one for elasticsearch instance and the other for laravel instance.
> Obviously the two containers were not "talking" each other.
> I solved creating a network between these different container and using the local IP (172. ...) assigned to the elasticsearch one into the laravel instance.
> Now it works perfectly.

Sounds good! Before investigation I every time check my environment. In most cases, problems are related to the environment.

**Comment by amitleuva1987** [comment]
@valehasadli , @damianoi , I am using a single container for my laravel app and elastic search in my localhost. I am receiving 'No Alive nodes found in your cluster'. Below is my docker-compose.yml

```
version: "3"
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        image: sail-8.1/app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "${APP_PORT:-80}:80"
            - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
            XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
            XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
        volumes:
            - ".:/var/www/html"
        networks:
            - sail
        depends_on:
            - mysql
            - redis
            - meilisearch
            - mailhog
            - selenium
    mysql:
        image: "mysql/mysql-server:8.0"
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - "sail-mysql:/var/lib/mysql"
            - "./vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    redis:
        image: "redis:alpine"
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - "sail-redis:/data"
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    meilisearch:
        image: "getmeili/meilisearch:latest"
        ports:
            - "${FORWARD_MEILISEARCH_PORT:-7700}:7700"
        volumes:
            - "sail-meilisearch:/meili_data"
        networks:
            - sail
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--no-verbose",
                    "--spider",
                    "http://localhost:7700/health",
                ]
            retries: 3
            timeout: 5s
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
        environment:
            - discovery.type=single-node
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - sailelasticsearch:/usr/share/elasticsearch/data
        networks:
            - sail
    mailhog:
        image: "mailhog/mailhog:latest"
        ports:
            - "${FORWARD_MAILHOG_PORT:-1025}:1025"
            - "${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025"
        networks:
            - sail
    selenium:
        image: "selenium/standalone-chrome"
        volumes:
            - "/dev/shm:/dev/shm"
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
    sailelasticsearch:
        driver: local

```

below is my client builder code.
    ```
use GuzzleHttp\Client as HttpClient;
    ClientBuilder::create()
                    ->setHttpClient(new HttpClient(['verify' => false ])) 
                    ->setHosts(['http://localhost:9200'])
                    ->build()
```
