### ISSUE TITLE
client->indices()->stats fails with "No alive nodes in your cluster" exception

### ISSUE THREAD

**Issue by FxNion** [elastic/elasticsearch-php#1146]
### Summary of problem or feature request

The call to indices->stats(INDEX_NAME) throw an Exception "No alive nodes in your cluster"
The cluster is single node, and respond correctly to other client calls, through PHP client our curl

### Code snippet of problem

`$this->client->indices()->stats(['index'=>'es-index']);`

### System details

- Operating System : Debian buster / boot2docker
- PHP Version : 7.4
- ES-PHP client version :  7.3
- Elasticsearch version : 7.13

**Comment by ezimuel** [comment]
@FxNion can you post the PHP code that you are using to build the `$this->client` instance?
Can you also share the code that you mentioned working using other client?
Thanks.

**Comment by FxNion** [comment]
@ezimuel, here the whole things i found to help:

The docker-compose part (who knows):
```
elasticsearch-7:
    container_name: elasticsearch-7
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    restart: always 
    environment:
      - discovery.type=single-node
      - cluster.name=wabtch-es-docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G -Xlog:disable -Xlog:all=warning:stderr:utctime,level,tags -Xlog:gc=debug:stderr:utctime"
     ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - elasticsearch-7:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - backend
```

The php code used to create the client (truncated):

```
class ElasticRepository{

	protected $index, $host, $client;
	
	public function __construct($host, $index){
		$this->index = $index;
		$this->host = $host;
		$this->buildClient();
	}
	
	public function getIndexSize(){
		try {
			return (int)($this->client->indices()->stats(['index'=>$this->getIndexName()])['_all']['primaries']['store']['size_in_bytes'] / 1024 /1024 );
		}catch(\ Exception $e){
			error_log("getIndexSize : " . $e->getMessage());
			return 1024;
		}
	}
	
	public function getClient(){
		return $this->client;
	}
	
	public function getIndexName(){
		return $this->index;
	}
	
	protected function buildClient()  {
                $clientBuilder = \Elasticsearch\ClientBuilder::create();   // Instantiate a new ClientBuilder
                $clientBuilder->setHosts([$this->host]);           // Set the hosts
                $this->client = $clientBuilder->build();          // Build the client object
        }
// Other code, truncated ...
}

//To obtain index size, use the stat endpoint ...
$params = [
    'host' => config('elastic.host'),
    'port' => config('elastic.port'),
    'user' => config('elastic.username'),
    'pass' => config('elastic.password')
];

$esRepository= new ElasticRepository($params, 'the_cool_project'); 
$stats = $esRepository->getIndexSize();

```
And when the stat portion of code fails, i do search queries in my apps, using the same classes, but also just doing a query to the catalog endpoint to check wether nodes are really dead (they are alive): 

`docker exec -it elasticsearch-7 curl http://localhost:9200/_cat/indices?v`

Or even, the stat endpoint, which is successfull

`docker exec -it elasticsearch-7 curl http://localhost:9200/_stats`

Hope this helps,
Regards
