### ISSUE TITLE
No alive nodes. All the 1 nodes seem to be down.

### ISSUE THREAD

**Issue by amitleuva1987** [elastic/elasticsearch-php#1250]
### Summary of problem or feature request

I am using Laravel 9. White connecting elastic search (running over docker)., I couldn't connect through Laravel application. I can see it running over http://localhost:9200. I can also see it running using curl.  Below is sample code

```
$client = Elastic\Elasticsearch\ClientBuilder::create()->build();
    
    $params = array();
    $params['body']  = array(	
    'name' => 'amit', 											//preparing structred data
    'age' => 'leuva'
    
    );
    $params['index'] = 'BeyBlade';
    $params['type']  = 'BeyBlade_Owner';
    $result = $client->index($params);							//using Index() function to inject the data
    var_dump($result);
```

Below is the error trace.

```
[2022-09-08 04:42:55] local.ERROR: No alive nodes. All the 1 nodes seem to be down. {"exception":"[object] (Elastic\\Transport\\Exception\\NoNodeAvailableException(code: 0): No alive nodes. All the 1 nodes seem to be down. at /var/www/html/vendor/elastic/transport/src/NodePool/SimpleNodePool.php:77)
[stacktrace]
#0 /var/www/html/vendor/elastic/transport/src/Transport.php(290): Elastic\\Transport\\NodePool\\SimpleNodePool->nextNode()
#1 /var/www/html/vendor/elasticsearch/elasticsearch/src/Client.php(168): Elastic\\Transport\\Transport->sendRequest()
#2 /var/www/html/vendor/elasticsearch/elasticsearch/src/Traits/ClientEndpointsTrait.php(77): Elastic\\Elasticsearch\\Client->sendRequest()
#3 /var/www/html/vendor/tamayo/laravel-scout-elastic/src/Engines/ElasticsearchEngine.php(87): Elastic\\Elasticsearch\\Client->bulk()
#4 /var/www/html/vendor/laravel/scout/src/Searchable.php(62): Tamayo\\LaravelScoutElastic\\Engines\\ElasticsearchEngine->update()
#5 /var/www/html/vendor/laravel/scout/src/Searchable.php(41): App\\Models\\Product->queueMakeSearchable()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php(124): Illuminate\\Database\\Eloquent\\Collection->Laravel\\Scout\\{closure}()
#7 /var/www/html/vendor/laravel/scout/src/SearchableScope.php(36): Illuminate\\Support\\Collection->__call()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(141): Laravel\\Scout\\SearchableScope->Laravel\\Scout\\{closure}()
#9 /var/www/html/vendor/laravel/scout/src/SearchableScope.php(39): Illuminate\\Database\\Eloquent\\Builder->chunkById()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1840): Laravel\\Scout\\SearchableScope->Laravel\\Scout\\{closure}()
#11 /var/www/html/vendor/laravel/scout/src/Searchable.php(148): Illuminate\\Database\\Eloquent\\Builder->__call()
#12 /var/www/html/vendor/laravel/scout/src/Console/ImportCommand.php(45): App\\Models\\Product::makeAllSearchable()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Scout\\Console\\ImportCommand->handle()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(144): Illuminate\\Container\\Container->call()
#19 /var/www/html/vendor/symfony/console/Command/Command.php(308): Illuminate\\Console\\Command->execute()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(126): Symfony\\Component\\Console\\Command\\Command->run()
#21 /var/www/html/vendor/symfony/console/Application.php(1002): Illuminate\\Console\\Command->run()
#22 /var/www/html/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#23 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#26 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#27 {main}
"} 

```

### Code snippet of problem

I have tried below codes

```
ClientBuilder::create()
                    ->setHosts(['http://localhost:9200'])
                    ->build()
```

```
ClientBuilder::create()
                    ->setHosts(['elasticsearch'])
                    ->build()
```

below is my docker-compose.yml

```
version: "3"
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        image: sail-8.1/app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "${APP_PORT:-80}:80"
            - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
            XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
            XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
        volumes:
            - ".:/var/www/html"
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: "mysql/mysql-server:8.0"
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - "sail-mysql:/var/lib/mysql"
            - "./vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
        environment:
            - discovery.type=single-node
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - sailelasticsearch:/usr/share/elasticsearch/data
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sailelasticsearch:
        driver: local

```
### System details

- Operating System : Windows 11
- PHP Version : 8.0.2
- ES-PHP client version : 
- Elasticsearch version : 8.4
